---
title: "Alogaritma k-means"
date: "`r Sys.Date()`"
author: Rahayu dwiastuti pujiningrum-Institut Teknologi Statistika dan Bisnis Muhammadiyah
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
bibliography: references.bib
---

```{=html}
<style>
body{
text-align: justify}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Alogaritma k-means
   K-Means merupakan alogaritma yang membentuk paramenter input sebanyak k dan membagi sekumpulan n objek kedalam k cluster sehingga tingkat kemiringan anggota dalam satu cluster tinggi kemiringan antara anggota dalam satu cluster tinggi sedangkan tinggi kemiringan dengan anggota pada cluster lain sangat rendan. 

# Tahapan alogaritma k-means
1.Tentukan juSiapkan data set
2.mlah kelompok
3.Alokasikan data ke dalam kelompok secara acak
4.Hitung pusat kelompok (sentoid/rata-rata) dari data yang ada di Masing-masing   kelompok
5.Alokasikan masing-masing data ke sentroid/rata-rata terdekat
6.Kembali ke langakah 3.


# Eksperimen alogaritma k-means


# Replication Requieremnts
   Untuk melakukan Analysis ini, package yang diperlukan ialah:
```{r=FALSE}
library(readr)
library(dplyr)
```
 



# Referensi




